name: Go

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: user
      DB_USER: root
      DB_PASSWORD: ""
    
    steps:
      - name: "Mysql set up"
        run : |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DB_DATABASE ${{env.DB_DATABASE}};' -u${{env.DB_USER}} -p{{env.DB_PASSWORD}}

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: "Test"
        run: go test -v ./...

      - name: "Go build"
        run: go build -o ./user .

      - name: "Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: user-microservice
          path: user