name: Go

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: Ilovegolang@7
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: user
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        MYSQL_HOST: user_database
        MYSQL_PORT: 3306
        MYSQL_ROOT_PASSWORD: Ilovegolang@7

  # tag:
  #   name: Tag
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   outputs:
  #     new_tag: ${{ steps.tag_version.outputs.new_tag }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Bump version and push tag
  #       id: tag_version
  #       uses: mathieudutour/github-tag-action@v5.1
  #       with:
  #         github_token: ${{ secrets.GITHUBTOKEN }}
  #         tag_prefix: 


  docker:
    name: Build Docker Image
    # needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/usermicroservice